#include "cpu.h"

namespace gb {

uint Cpu_::Opcode_00() { return 4; }
uint Cpu_::Opcode_01() { return 4; }
uint Cpu_::Opcode_02() { return 4; }
uint Cpu_::Opcode_03() { return 4; }
uint Cpu_::Opcode_04() { return 4; }
uint Cpu_::Opcode_05() { return 4; }
uint Cpu_::Opcode_06() { return 4; }
uint Cpu_::Opcode_07() { return 4; }
uint Cpu_::Opcode_08() { return 4; }
uint Cpu_::Opcode_09() { return 4; }
uint Cpu_::Opcode_0A() { return 4; }
uint Cpu_::Opcode_0B() { return 4; }
uint Cpu_::Opcode_0C() { return 4; }
uint Cpu_::Opcode_0D() { return 4; }
uint Cpu_::Opcode_0E() { return 4; }
uint Cpu_::Opcode_0F() { return 4; }
uint Cpu_::Opcode_10() { return 4; }
uint Cpu_::Opcode_11() { return 4; }
uint Cpu_::Opcode_12() { return 4; }
uint Cpu_::Opcode_13() { return 4; }
uint Cpu_::Opcode_14() { return 4; }
uint Cpu_::Opcode_15() { return 4; }
uint Cpu_::Opcode_16() { return 4; }
uint Cpu_::Opcode_17() { return 4; }
uint Cpu_::Opcode_18() { return 4; }
uint Cpu_::Opcode_19() { return 4; }
uint Cpu_::Opcode_1A() { return 4; }
uint Cpu_::Opcode_1B() { return 4; }
uint Cpu_::Opcode_1C() { return 4; }
uint Cpu_::Opcode_1D() { return 4; }
uint Cpu_::Opcode_1E() { return 4; }
uint Cpu_::Opcode_1F() { return 4; }
uint Cpu_::Opcode_20() { return 4; }
uint Cpu_::Opcode_21() { return 4; }
uint Cpu_::Opcode_22() { return 4; }
uint Cpu_::Opcode_23() { return 4; }
uint Cpu_::Opcode_24() { return 4; }
uint Cpu_::Opcode_25() { return 4; }
uint Cpu_::Opcode_26() { return 4; }
uint Cpu_::Opcode_27() { return 4; }
uint Cpu_::Opcode_28() { return 4; }
uint Cpu_::Opcode_29() { return 4; }
uint Cpu_::Opcode_2A() { return 4; }
uint Cpu_::Opcode_2B() { return 4; }
uint Cpu_::Opcode_2C() { return 4; }
uint Cpu_::Opcode_2D() { return 4; }
uint Cpu_::Opcode_2E() { return 4; }
uint Cpu_::Opcode_2F() { return 4; }
uint Cpu_::Opcode_30() { return 4; }
uint Cpu_::Opcode_31() { return 4; }
uint Cpu_::Opcode_32() { return 4; }
uint Cpu_::Opcode_33() { return 4; }
uint Cpu_::Opcode_34() { return 4; }
uint Cpu_::Opcode_35() { return 4; }
uint Cpu_::Opcode_36() { return 4; }
uint Cpu_::Opcode_37() { return 4; }
uint Cpu_::Opcode_38() { return 4; }
uint Cpu_::Opcode_39() { return 4; }
uint Cpu_::Opcode_3A() { return 4; }
uint Cpu_::Opcode_3B() { return 4; }
uint Cpu_::Opcode_3C() { return 4; }
uint Cpu_::Opcode_3D() { return 4; }
uint Cpu_::Opcode_3E() { return 4; }
uint Cpu_::Opcode_3F() { return 4; }
uint Cpu_::Opcode_40() { return 4; }
uint Cpu_::Opcode_41() { return 4; }
uint Cpu_::Opcode_42() { return 4; }
uint Cpu_::Opcode_43() { return 4; }
uint Cpu_::Opcode_44() { return 4; }
uint Cpu_::Opcode_45() { return 4; }
uint Cpu_::Opcode_46() { return 4; }
uint Cpu_::Opcode_47() { return 4; }
uint Cpu_::Opcode_48() { return 4; }
uint Cpu_::Opcode_49() { return 4; }
uint Cpu_::Opcode_4A() { return 4; }
uint Cpu_::Opcode_4B() { return 4; }
uint Cpu_::Opcode_4C() { return 4; }
uint Cpu_::Opcode_4D() { return 4; }
uint Cpu_::Opcode_4E() { return 4; }
uint Cpu_::Opcode_4F() { return 4; }
uint Cpu_::Opcode_50() { return 4; }
uint Cpu_::Opcode_51() { return 4; }
uint Cpu_::Opcode_52() { return 4; }
uint Cpu_::Opcode_53() { return 4; }
uint Cpu_::Opcode_54() { return 4; }
uint Cpu_::Opcode_55() { return 4; }
uint Cpu_::Opcode_56() { return 4; }
uint Cpu_::Opcode_57() { return 4; }
uint Cpu_::Opcode_58() { return 4; }
uint Cpu_::Opcode_59() { return 4; }
uint Cpu_::Opcode_5A() { return 4; }
uint Cpu_::Opcode_5B() { return 4; }
uint Cpu_::Opcode_5C() { return 4; }
uint Cpu_::Opcode_5D() { return 4; }
uint Cpu_::Opcode_5E() { return 4; }
uint Cpu_::Opcode_5F() { return 4; }
uint Cpu_::Opcode_60() { return 4; }
uint Cpu_::Opcode_61() { return 4; }
uint Cpu_::Opcode_62() { return 4; }
uint Cpu_::Opcode_63() { return 4; }
uint Cpu_::Opcode_64() { return 4; }
uint Cpu_::Opcode_65() { return 4; }
uint Cpu_::Opcode_66() { return 4; }
uint Cpu_::Opcode_67() { return 4; }
uint Cpu_::Opcode_68() { return 4; }
uint Cpu_::Opcode_69() { return 4; }
uint Cpu_::Opcode_6A() { return 4; }
uint Cpu_::Opcode_6B() { return 4; }
uint Cpu_::Opcode_6C() { return 4; }
uint Cpu_::Opcode_6D() { return 4; }
uint Cpu_::Opcode_6E() { return 4; }
uint Cpu_::Opcode_6F() { return 4; }
uint Cpu_::Opcode_70() { return 4; }
uint Cpu_::Opcode_71() { return 4; }
uint Cpu_::Opcode_72() { return 4; }
uint Cpu_::Opcode_73() { return 4; }
uint Cpu_::Opcode_74() { return 4; }
uint Cpu_::Opcode_75() { return 4; }
uint Cpu_::Opcode_76() { return 4; }
uint Cpu_::Opcode_77() { return 4; }
uint Cpu_::Opcode_78() { return 4; }
uint Cpu_::Opcode_79() { return 4; }
uint Cpu_::Opcode_7A() { return 4; }
uint Cpu_::Opcode_7B() { return 4; }
uint Cpu_::Opcode_7C() { return 4; }
uint Cpu_::Opcode_7D() { return 4; }
uint Cpu_::Opcode_7E() { return 4; }
uint Cpu_::Opcode_7F() { return 4; }
uint Cpu_::Opcode_80() { return 4; }
uint Cpu_::Opcode_81() { return 4; }
uint Cpu_::Opcode_82() { return 4; }
uint Cpu_::Opcode_83() { return 4; }
uint Cpu_::Opcode_84() { return 4; }
uint Cpu_::Opcode_85() { return 4; }
uint Cpu_::Opcode_86() { return 4; }
uint Cpu_::Opcode_87() { return 4; }
uint Cpu_::Opcode_88() { return 4; }
uint Cpu_::Opcode_89() { return 4; }
uint Cpu_::Opcode_8A() { return 4; }
uint Cpu_::Opcode_8B() { return 4; }
uint Cpu_::Opcode_8C() { return 4; }
uint Cpu_::Opcode_8D() { return 4; }
uint Cpu_::Opcode_8E() { return 4; }
uint Cpu_::Opcode_8F() { return 4; }
uint Cpu_::Opcode_90() { return 4; }
uint Cpu_::Opcode_91() { return 4; }
uint Cpu_::Opcode_92() { return 4; }
uint Cpu_::Opcode_93() { return 4; }
uint Cpu_::Opcode_94() { return 4; }
uint Cpu_::Opcode_95() { return 4; }
uint Cpu_::Opcode_96() { return 4; }
uint Cpu_::Opcode_97() { return 4; }
uint Cpu_::Opcode_98() { return 4; }
uint Cpu_::Opcode_99() { return 4; }
uint Cpu_::Opcode_9A() { return 4; }
uint Cpu_::Opcode_9B() { return 4; }
uint Cpu_::Opcode_9C() { return 4; }
uint Cpu_::Opcode_9D() { return 4; }
uint Cpu_::Opcode_9E() { return 4; }
uint Cpu_::Opcode_9F() { return 4; }
uint Cpu_::Opcode_A0() { return 4; }
uint Cpu_::Opcode_A1() { return 4; }
uint Cpu_::Opcode_A2() { return 4; }
uint Cpu_::Opcode_A3() { return 4; }
uint Cpu_::Opcode_A4() { return 4; }
uint Cpu_::Opcode_A5() { return 4; }
uint Cpu_::Opcode_A6() { return 4; }
uint Cpu_::Opcode_A7() { return 4; }
uint Cpu_::Opcode_A8() { return 4; }
uint Cpu_::Opcode_A9() { return 4; }
uint Cpu_::Opcode_AA() { return 4; }
uint Cpu_::Opcode_AB() { return 4; }
uint Cpu_::Opcode_AC() { return 4; }
uint Cpu_::Opcode_AD() { return 4; }
uint Cpu_::Opcode_AE() { return 4; }
uint Cpu_::Opcode_AF() { return 4; }
uint Cpu_::Opcode_B0() { return 4; }
uint Cpu_::Opcode_B1() { return 4; }
uint Cpu_::Opcode_B2() { return 4; }
uint Cpu_::Opcode_B3() { return 4; }
uint Cpu_::Opcode_B4() { return 4; }
uint Cpu_::Opcode_B5() { return 4; }
uint Cpu_::Opcode_B6() { return 4; }
uint Cpu_::Opcode_B7() { return 4; }
uint Cpu_::Opcode_B8() { return 4; }
uint Cpu_::Opcode_B9() { return 4; }
uint Cpu_::Opcode_BA() { return 4; }
uint Cpu_::Opcode_BB() { return 4; }
uint Cpu_::Opcode_BC() { return 4; }
uint Cpu_::Opcode_BD() { return 4; }
uint Cpu_::Opcode_BE() { return 4; }
uint Cpu_::Opcode_BF() { return 4; }
uint Cpu_::Opcode_C0() { return 4; }
uint Cpu_::Opcode_C1() { return 4; }
uint Cpu_::Opcode_C2() { return 4; }
uint Cpu_::Opcode_C3() { return 4; }
uint Cpu_::Opcode_C4() { return 4; }
uint Cpu_::Opcode_C5() { return 4; }
uint Cpu_::Opcode_C6() { return 4; }
uint Cpu_::Opcode_C7() { return 4; }
uint Cpu_::Opcode_C8() { return 4; }
uint Cpu_::Opcode_C9() { return 4; }
uint Cpu_::Opcode_CA() { return 4; }
uint Cpu_::Opcode_CB() { return 4; }
uint Cpu_::Opcode_CC() { return 4; }
uint Cpu_::Opcode_CD() { return 4; }
uint Cpu_::Opcode_CE() { return 4; }
uint Cpu_::Opcode_CF() { return 4; }
uint Cpu_::Opcode_D0() { return 4; }
uint Cpu_::Opcode_D1() { return 4; }
uint Cpu_::Opcode_D2() { return 4; }
uint Cpu_::Opcode_D3() { return 4; }
uint Cpu_::Opcode_D4() { return 4; }
uint Cpu_::Opcode_D5() { return 4; }
uint Cpu_::Opcode_D6() { return 4; }
uint Cpu_::Opcode_D7() { return 4; }
uint Cpu_::Opcode_D8() { return 4; }
uint Cpu_::Opcode_D9() { return 4; }
uint Cpu_::Opcode_DA() { return 4; }
uint Cpu_::Opcode_DB() { return 4; }
uint Cpu_::Opcode_DC() { return 4; }
uint Cpu_::Opcode_DD() { return 4; }
uint Cpu_::Opcode_DE() { return 4; }
uint Cpu_::Opcode_E0() { return 4; }
uint Cpu_::Opcode_DF() { return 4; }
uint Cpu_::Opcode_E1() { return 4; }
uint Cpu_::Opcode_E2() { return 4; }
uint Cpu_::Opcode_E3() { return 4; }
uint Cpu_::Opcode_E4() { return 4; }
uint Cpu_::Opcode_E5() { return 4; }
uint Cpu_::Opcode_E6() { return 4; }
uint Cpu_::Opcode_E7() { return 4; }
uint Cpu_::Opcode_E8() { return 4; }
uint Cpu_::Opcode_E9() { return 4; }
uint Cpu_::Opcode_EA() { return 4; }
uint Cpu_::Opcode_EB() { return 4; }
uint Cpu_::Opcode_EC() { return 4; }
uint Cpu_::Opcode_ED() { return 4; }
uint Cpu_::Opcode_EE() { return 4; }
uint Cpu_::Opcode_EF() { return 4; }
uint Cpu_::Opcode_F0() { return 4; }
uint Cpu_::Opcode_F1() { return 4; }
uint Cpu_::Opcode_F2() { return 4; }
uint Cpu_::Opcode_F3() { return 4; }
uint Cpu_::Opcode_F4() { return 4; }
uint Cpu_::Opcode_F5() { return 4; }
uint Cpu_::Opcode_F6() { return 4; }
uint Cpu_::Opcode_F7() { return 4; }
uint Cpu_::Opcode_F8() { return 4; }
uint Cpu_::Opcode_F9() { return 4; }
uint Cpu_::Opcode_FA() { return 4; }
uint Cpu_::Opcode_FB() { return 4; }
uint Cpu_::Opcode_FC() { return 4; }
uint Cpu_::Opcode_FD() { return 4; }
uint Cpu_::Opcode_FE() { return 4; }
uint Cpu_::Opcode_FF() { return 4; }
uint Cpu_::Opcode_CB_00() { return 4; }
uint Cpu_::Opcode_CB_01() { return 4; }
uint Cpu_::Opcode_CB_02() { return 4; }
uint Cpu_::Opcode_CB_03() { return 4; }
uint Cpu_::Opcode_CB_04() { return 4; }
uint Cpu_::Opcode_CB_05() { return 4; }
uint Cpu_::Opcode_CB_06() { return 4; }
uint Cpu_::Opcode_CB_07() { return 4; }
uint Cpu_::Opcode_CB_08() { return 4; }
uint Cpu_::Opcode_CB_09() { return 4; }
uint Cpu_::Opcode_CB_0A() { return 4; }
uint Cpu_::Opcode_CB_0B() { return 4; }
uint Cpu_::Opcode_CB_0C() { return 4; }
uint Cpu_::Opcode_CB_0D() { return 4; }
uint Cpu_::Opcode_CB_0E() { return 4; }
uint Cpu_::Opcode_CB_0F() { return 4; }
uint Cpu_::Opcode_CB_10() { return 4; }
uint Cpu_::Opcode_CB_11() { return 4; }
uint Cpu_::Opcode_CB_12() { return 4; }
uint Cpu_::Opcode_CB_13() { return 4; }
uint Cpu_::Opcode_CB_14() { return 4; }
uint Cpu_::Opcode_CB_15() { return 4; }
uint Cpu_::Opcode_CB_16() { return 4; }
uint Cpu_::Opcode_CB_17() { return 4; }
uint Cpu_::Opcode_CB_18() { return 4; }
uint Cpu_::Opcode_CB_19() { return 4; }
uint Cpu_::Opcode_CB_1A() { return 4; }
uint Cpu_::Opcode_CB_1B() { return 4; }
uint Cpu_::Opcode_CB_1C() { return 4; }
uint Cpu_::Opcode_CB_1D() { return 4; }
uint Cpu_::Opcode_CB_1E() { return 4; }
uint Cpu_::Opcode_CB_1F() { return 4; }
uint Cpu_::Opcode_CB_20() { return 4; }
uint Cpu_::Opcode_CB_21() { return 4; }
uint Cpu_::Opcode_CB_22() { return 4; }
uint Cpu_::Opcode_CB_23() { return 4; }
uint Cpu_::Opcode_CB_24() { return 4; }
uint Cpu_::Opcode_CB_25() { return 4; }
uint Cpu_::Opcode_CB_26() { return 4; }
uint Cpu_::Opcode_CB_27() { return 4; }
uint Cpu_::Opcode_CB_28() { return 4; }
uint Cpu_::Opcode_CB_29() { return 4; }
uint Cpu_::Opcode_CB_2A() { return 4; }
uint Cpu_::Opcode_CB_2B() { return 4; }
uint Cpu_::Opcode_CB_2C() { return 4; }
uint Cpu_::Opcode_CB_2D() { return 4; }
uint Cpu_::Opcode_CB_2E() { return 4; }
uint Cpu_::Opcode_CB_2F() { return 4; }
uint Cpu_::Opcode_CB_30() { return 4; }
uint Cpu_::Opcode_CB_31() { return 4; }
uint Cpu_::Opcode_CB_32() { return 4; }
uint Cpu_::Opcode_CB_33() { return 4; }
uint Cpu_::Opcode_CB_34() { return 4; }
uint Cpu_::Opcode_CB_35() { return 4; }
uint Cpu_::Opcode_CB_36() { return 4; }
uint Cpu_::Opcode_CB_37() { return 4; }
uint Cpu_::Opcode_CB_38() { return 4; }
uint Cpu_::Opcode_CB_39() { return 4; }
uint Cpu_::Opcode_CB_3A() { return 4; }
uint Cpu_::Opcode_CB_3B() { return 4; }
uint Cpu_::Opcode_CB_3C() { return 4; }
uint Cpu_::Opcode_CB_3D() { return 4; }
uint Cpu_::Opcode_CB_3E() { return 4; }
uint Cpu_::Opcode_CB_3F() { return 4; }
uint Cpu_::Opcode_CB_40() { return 4; }
uint Cpu_::Opcode_CB_41() { return 4; }
uint Cpu_::Opcode_CB_42() { return 4; }
uint Cpu_::Opcode_CB_43() { return 4; }
uint Cpu_::Opcode_CB_44() { return 4; }
uint Cpu_::Opcode_CB_45() { return 4; }
uint Cpu_::Opcode_CB_46() { return 4; }
uint Cpu_::Opcode_CB_47() { return 4; }
uint Cpu_::Opcode_CB_48() { return 4; }
uint Cpu_::Opcode_CB_49() { return 4; }
uint Cpu_::Opcode_CB_4A() { return 4; }
uint Cpu_::Opcode_CB_4B() { return 4; }
uint Cpu_::Opcode_CB_4C() { return 4; }
uint Cpu_::Opcode_CB_4D() { return 4; }
uint Cpu_::Opcode_CB_4E() { return 4; }
uint Cpu_::Opcode_CB_4F() { return 4; }
uint Cpu_::Opcode_CB_50() { return 4; }
uint Cpu_::Opcode_CB_51() { return 4; }
uint Cpu_::Opcode_CB_52() { return 4; }
uint Cpu_::Opcode_CB_53() { return 4; }
uint Cpu_::Opcode_CB_54() { return 4; }
uint Cpu_::Opcode_CB_55() { return 4; }
uint Cpu_::Opcode_CB_56() { return 4; }
uint Cpu_::Opcode_CB_57() { return 4; }
uint Cpu_::Opcode_CB_58() { return 4; }
uint Cpu_::Opcode_CB_59() { return 4; }
uint Cpu_::Opcode_CB_5A() { return 4; }
uint Cpu_::Opcode_CB_5B() { return 4; }
uint Cpu_::Opcode_CB_5C() { return 4; }
uint Cpu_::Opcode_CB_5D() { return 4; }
uint Cpu_::Opcode_CB_5E() { return 4; }
uint Cpu_::Opcode_CB_5F() { return 4; }
uint Cpu_::Opcode_CB_60() { return 4; }
uint Cpu_::Opcode_CB_61() { return 4; }
uint Cpu_::Opcode_CB_62() { return 4; }
uint Cpu_::Opcode_CB_63() { return 4; }
uint Cpu_::Opcode_CB_64() { return 4; }
uint Cpu_::Opcode_CB_65() { return 4; }
uint Cpu_::Opcode_CB_66() { return 4; }
uint Cpu_::Opcode_CB_67() { return 4; }
uint Cpu_::Opcode_CB_68() { return 4; }
uint Cpu_::Opcode_CB_69() { return 4; }
uint Cpu_::Opcode_CB_6A() { return 4; }
uint Cpu_::Opcode_CB_6B() { return 4; }
uint Cpu_::Opcode_CB_6C() { return 4; }
uint Cpu_::Opcode_CB_6D() { return 4; }
uint Cpu_::Opcode_CB_6E() { return 4; }
uint Cpu_::Opcode_CB_6F() { return 4; }
uint Cpu_::Opcode_CB_70() { return 4; }
uint Cpu_::Opcode_CB_71() { return 4; }
uint Cpu_::Opcode_CB_72() { return 4; }
uint Cpu_::Opcode_CB_73() { return 4; }
uint Cpu_::Opcode_CB_74() { return 4; }
uint Cpu_::Opcode_CB_75() { return 4; }
uint Cpu_::Opcode_CB_76() { return 4; }
uint Cpu_::Opcode_CB_77() { return 4; }
uint Cpu_::Opcode_CB_78() { return 4; }
uint Cpu_::Opcode_CB_79() { return 4; }
uint Cpu_::Opcode_CB_7A() { return 4; }
uint Cpu_::Opcode_CB_7B() { return 4; }
uint Cpu_::Opcode_CB_7C() { return 4; }
uint Cpu_::Opcode_CB_7D() { return 4; }
uint Cpu_::Opcode_CB_7E() { return 4; }
uint Cpu_::Opcode_CB_7F() { return 4; }
uint Cpu_::Opcode_CB_80() { return 4; }
uint Cpu_::Opcode_CB_81() { return 4; }
uint Cpu_::Opcode_CB_82() { return 4; }
uint Cpu_::Opcode_CB_83() { return 4; }
uint Cpu_::Opcode_CB_84() { return 4; }
uint Cpu_::Opcode_CB_85() { return 4; }
uint Cpu_::Opcode_CB_86() { return 4; }
uint Cpu_::Opcode_CB_87() { return 4; }
uint Cpu_::Opcode_CB_88() { return 4; }
uint Cpu_::Opcode_CB_89() { return 4; }
uint Cpu_::Opcode_CB_8A() { return 4; }
uint Cpu_::Opcode_CB_8B() { return 4; }
uint Cpu_::Opcode_CB_8C() { return 4; }
uint Cpu_::Opcode_CB_8D() { return 4; }
uint Cpu_::Opcode_CB_8E() { return 4; }
uint Cpu_::Opcode_CB_8F() { return 4; }
uint Cpu_::Opcode_CB_90() { return 4; }
uint Cpu_::Opcode_CB_91() { return 4; }
uint Cpu_::Opcode_CB_92() { return 4; }
uint Cpu_::Opcode_CB_93() { return 4; }
uint Cpu_::Opcode_CB_94() { return 4; }
uint Cpu_::Opcode_CB_95() { return 4; }
uint Cpu_::Opcode_CB_96() { return 4; }
uint Cpu_::Opcode_CB_97() { return 4; }
uint Cpu_::Opcode_CB_98() { return 4; }
uint Cpu_::Opcode_CB_99() { return 4; }
uint Cpu_::Opcode_CB_9A() { return 4; }
uint Cpu_::Opcode_CB_9B() { return 4; }
uint Cpu_::Opcode_CB_9C() { return 4; }
uint Cpu_::Opcode_CB_9D() { return 4; }
uint Cpu_::Opcode_CB_9E() { return 4; }
uint Cpu_::Opcode_CB_9F() { return 4; }
uint Cpu_::Opcode_CB_A0() { return 4; }
uint Cpu_::Opcode_CB_A1() { return 4; }
uint Cpu_::Opcode_CB_A2() { return 4; }
uint Cpu_::Opcode_CB_A3() { return 4; }
uint Cpu_::Opcode_CB_A4() { return 4; }
uint Cpu_::Opcode_CB_A5() { return 4; }
uint Cpu_::Opcode_CB_A6() { return 4; }
uint Cpu_::Opcode_CB_A7() { return 4; }
uint Cpu_::Opcode_CB_A8() { return 4; }
uint Cpu_::Opcode_CB_A9() { return 4; }
uint Cpu_::Opcode_CB_AA() { return 4; }
uint Cpu_::Opcode_CB_AB() { return 4; }
uint Cpu_::Opcode_CB_AC() { return 4; }
uint Cpu_::Opcode_CB_AD() { return 4; }
uint Cpu_::Opcode_CB_AE() { return 4; }
uint Cpu_::Opcode_CB_AF() { return 4; }
uint Cpu_::Opcode_CB_B0() { return 4; }
uint Cpu_::Opcode_CB_B1() { return 4; }
uint Cpu_::Opcode_CB_B2() { return 4; }
uint Cpu_::Opcode_CB_B3() { return 4; }
uint Cpu_::Opcode_CB_B4() { return 4; }
uint Cpu_::Opcode_CB_B5() { return 4; }
uint Cpu_::Opcode_CB_B6() { return 4; }
uint Cpu_::Opcode_CB_B7() { return 4; }
uint Cpu_::Opcode_CB_B8() { return 4; }
uint Cpu_::Opcode_CB_B9() { return 4; }
uint Cpu_::Opcode_CB_BA() { return 4; }
uint Cpu_::Opcode_CB_BB() { return 4; }
uint Cpu_::Opcode_CB_BC() { return 4; }
uint Cpu_::Opcode_CB_BD() { return 4; }
uint Cpu_::Opcode_CB_BE() { return 4; }
uint Cpu_::Opcode_CB_BF() { return 4; }
uint Cpu_::Opcode_CB_C0() { return 4; }
uint Cpu_::Opcode_CB_C1() { return 4; }
uint Cpu_::Opcode_CB_C2() { return 4; }
uint Cpu_::Opcode_CB_C3() { return 4; }
uint Cpu_::Opcode_CB_C4() { return 4; }
uint Cpu_::Opcode_CB_C5() { return 4; }
uint Cpu_::Opcode_CB_C6() { return 4; }
uint Cpu_::Opcode_CB_C7() { return 4; }
uint Cpu_::Opcode_CB_C8() { return 4; }
uint Cpu_::Opcode_CB_C9() { return 4; }
uint Cpu_::Opcode_CB_CA() { return 4; }
uint Cpu_::Opcode_CB_CB() { return 4; }
uint Cpu_::Opcode_CB_CC() { return 4; }
uint Cpu_::Opcode_CB_CD() { return 4; }
uint Cpu_::Opcode_CB_CE() { return 4; }
uint Cpu_::Opcode_CB_CF() { return 4; }
uint Cpu_::Opcode_CB_D0() { return 4; }
uint Cpu_::Opcode_CB_D1() { return 4; }
uint Cpu_::Opcode_CB_D2() { return 4; }
uint Cpu_::Opcode_CB_D3() { return 4; }
uint Cpu_::Opcode_CB_D4() { return 4; }
uint Cpu_::Opcode_CB_D5() { return 4; }
uint Cpu_::Opcode_CB_D6() { return 4; }
uint Cpu_::Opcode_CB_D7() { return 4; }
uint Cpu_::Opcode_CB_D8() { return 4; }
uint Cpu_::Opcode_CB_D9() { return 4; }
uint Cpu_::Opcode_CB_DA() { return 4; }
uint Cpu_::Opcode_CB_DB() { return 4; }
uint Cpu_::Opcode_CB_DC() { return 4; }
uint Cpu_::Opcode_CB_DD() { return 4; }
uint Cpu_::Opcode_CB_DE() { return 4; }
uint Cpu_::Opcode_CB_DF() { return 4; }
uint Cpu_::Opcode_CB_E0() { return 4; }
uint Cpu_::Opcode_CB_E1() { return 4; }
uint Cpu_::Opcode_CB_E2() { return 4; }
uint Cpu_::Opcode_CB_E3() { return 4; }
uint Cpu_::Opcode_CB_E4() { return 4; }
uint Cpu_::Opcode_CB_E5() { return 4; }
uint Cpu_::Opcode_CB_E6() { return 4; }
uint Cpu_::Opcode_CB_E7() { return 4; }
uint Cpu_::Opcode_CB_E8() { return 4; }
uint Cpu_::Opcode_CB_E9() { return 4; }
uint Cpu_::Opcode_CB_EA() { return 4; }
uint Cpu_::Opcode_CB_EB() { return 4; }
uint Cpu_::Opcode_CB_EC() { return 4; }
uint Cpu_::Opcode_CB_ED() { return 4; }
uint Cpu_::Opcode_CB_EE() { return 4; }
uint Cpu_::Opcode_CB_EF() { return 4; }
uint Cpu_::Opcode_CB_F0() { return 4; }
uint Cpu_::Opcode_CB_F1() { return 4; }
uint Cpu_::Opcode_CB_F2() { return 4; }
uint Cpu_::Opcode_CB_F3() { return 4; }
uint Cpu_::Opcode_CB_F4() { return 4; }
uint Cpu_::Opcode_CB_F5() { return 4; }
uint Cpu_::Opcode_CB_F6() { return 4; }
uint Cpu_::Opcode_CB_F7() { return 4; }
uint Cpu_::Opcode_CB_F8() { return 4; }
uint Cpu_::Opcode_CB_F9() { return 4; }
uint Cpu_::Opcode_CB_FA() { return 4; }
uint Cpu_::Opcode_CB_FB() { return 4; }
uint Cpu_::Opcode_CB_FC() { return 4; }
uint Cpu_::Opcode_CB_FD() { return 4; }
uint Cpu_::Opcode_CB_FE() { return 4; }
uint Cpu_::Opcode_CB_FF() { return 4; }

}
